import {
  House,
  HardDrive,
  Users,
  Star,
  Trash2,
  Calendar,
  CalendarPlus,
  SquareCheck,
  CircleCheck,
  FileText,
  Wallet,
  ChefHat,
  KeyRound,
  Image as ImageIcon,
  Utensils,
  Bookmark,
  Flame,
  Bell,
  Sun,
  Moon,
  Upload,
  Search,
  Plus,
  ChevronDown,
  Cloud,
  PanelLeft,
  MoreHorizontal,
  Filter,
  List,
  LayoutGrid,
  Columns3,
  PanelRight,
  Share2,
  Download,
  Settings,
  LogOut,
  Puzzle,
  GitBranch,
  Sparkles,
  Tag,
  BookOpen,
  Folder,
  Package,
  ChevronRight,
  ChevronLeft,
  Hash,
  Database,
  Globe,
  Archive,
  NotebookText,
  CloudOff,
  Link2,
  RotateCcw,
  Pencil,
  Eye,
  EyeOff,
  X,
  Maximize2,
  Minimize2,
  type LucideIcon,
} from "lucide-react";
import type { CSSProperties } from "react";

const MAP: Record<string, LucideIcon> = {
  x: X,
  home: House,
  "my-drive": HardDrive,
  family: Users,
  users: Users,
  starred: Star,
  star: Star,
  trash: Trash2,
  calendar: Calendar,
  "calendar-plus": CalendarPlus,
  "check-square": SquareCheck,
  "circle-check": CircleCheck,
  "file-text": FileText,
  wallet: Wallet,
  "chef-hat": ChefHat,
  "key-round": KeyRound,
  image: ImageIcon,
  utensils: Utensils,
  bookmark: Bookmark,
  flame: Flame,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  upload: Upload,
  search: Search,
  plus: Plus,
  "chevron-down": ChevronDown,
  cloud: Cloud,
  "panel-left": PanelLeft,
  more: MoreHorizontal,
  filter: Filter,
  list: List,
  grid: LayoutGrid,
  board: Columns3,
  "panel-right": PanelRight,
  share: Share2,
  download: Download,
  settings: Settings,
  "log-out": LogOut,
  plugin: Puzzle,
  github: GitBranch,
  sparkles: Sparkles,
  tag: Tag,
  book: BookOpen,
  folder: Folder,
  package: Package,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  hash: Hash,
  database: Database,
  globe: Globe,
  archive: Archive,
  note: NotebookText,
  "cloud-off": CloudOff,
  link: Link2,
  restore: RotateCcw,
  edit: Pencil,
  eye: Eye,
  "eye-off": EyeOff,
  maximize: Maximize2,
  minimize: Minimize2,
};

export function Icon({
  name,
  size = 16,
  strokeWidth = 1.75,
  className,
  style,
}: {
  name: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: CSSProperties;
}) {
  const Cmp = MAP[name] ?? Puzzle;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} style={style} />;
}
