import type { Db } from "./db";

/**
 * A plugin authored at runtime in the Plugin Studio (generated by the core LLM),
 * owned by the user who built it. The store keeps both the manifest and the ESM
 * entry source — they don't ship with the host like catalog plugins do. The
 * `manifest` is an **opaque JSON string** as far as the store is concerned (the
 * API/client parse it); the store never inspects it.
 */
export interface CustomPlugin {
  id: string;
  /** The plugin manifest, serialized — parsed by the API/client, not the store. */
  manifest: string;
  /** ESM source for the sandboxed viewer entry module. */
  source: string;
  createdAt: string;
  updatedAt: string;
}

interface Row {
  plugin_id: string;
  manifest_json: string;
  source_text: string;
  created_at: string;
  updated_at: string;
}

const toCustomPlugin = (r: Row): CustomPlugin => ({
  id: r.plugin_id,
  manifest: r.manifest_json,
  source: r.source_text,
  createdAt: r.created_at,
  updatedAt: r.updated_at,
});

export async function listCustomPlugins(db: Db, userSub: string): Promise<CustomPlugin[]> {
  const rows = await db.all<Row>(
    "SELECT plugin_id, manifest_json, source_text, created_at, updated_at FROM custom_plugins WHERE user_sub = ? ORDER BY created_at",
    [userSub],
  );
  return rows.map(toCustomPlugin);
}

export async function getCustomPlugin(db: Db, userSub: string, pluginId: string): Promise<CustomPlugin | null> {
  const row = await db.first<Row>(
    "SELECT plugin_id, manifest_json, source_text, created_at, updated_at FROM custom_plugins WHERE user_sub = ? AND plugin_id = ?",
    [userSub, pluginId],
  );
  return row ? toCustomPlugin(row) : null;
}

/** Insert or replace a generated plugin (manifest + source). `created_at` is preserved on update. */
export async function upsertCustomPlugin(
  db: Db,
  userSub: string,
  input: { id: string; manifest: string; source: string },
): Promise<void> {
  const now = new Date().toISOString();
  await db.run(
    "INSERT INTO custom_plugins (user_sub, plugin_id, manifest_json, source_text, created_at, updated_at) " +
      "VALUES (?, ?, ?, ?, ?, ?) " +
      "ON CONFLICT(user_sub, plugin_id) DO UPDATE SET manifest_json = excluded.manifest_json, " +
      "source_text = excluded.source_text, updated_at = excluded.updated_at",
    [userSub, input.id, input.manifest, input.source, now, now],
  );
}

export async function deleteCustomPlugin(db: Db, userSub: string, pluginId: string): Promise<void> {
  await db.run("DELETE FROM custom_plugins WHERE user_sub = ? AND plugin_id = ?", [userSub, pluginId]);
}
