import { afterEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { ShareDialog } from './share-dialog';
import { CopyFolderLink } from './copy-folder-link';
import * as api from './api';
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); api.selectSite(null); });
it('copies a credential-free navigation link from the share dialog without granting access', async () => {
  api.selectSite('family');
  const fetch = vi.fn(async (url: string, init?: RequestInit) => new Response(JSON.stringify(url.endsWith('/shares') ? { shares: [] } : url.endsWith('/people') ? { people: [] } : { id: 'reports', name: 'Reports', path: 'Team/Reports & notes' })));
  vi.stubGlobal('fetch', fetch);
  const writeText = vi.fn(async (_text: string) => {});
  vi.stubGlobal('navigator', { clipboard: { writeText } });
  render(<ShareDialog folder={{ id: 'reports', name: 'Reports' }} onClose={() => {}} />);
  await waitFor(() => expect(screen.getByRole('button', { name: 'Copy folder link' }).hasAttribute('disabled')).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Copy folder link' }));
  await screen.findByText('Folder link copied.');
  const link = new URL(writeText.mock.calls[0]![0]);
  expect(link.searchParams.get('site')).toBe('family');
  expect(link.searchParams.get('folder')).toBe('reports');
  expect(link.searchParams.has('path')).toBe(false);
  expect([...link.searchParams.keys()]).toEqual(['site', 'folder']);
  expect(fetch.mock.calls.every(([, init]) => !init?.method || init.method === 'GET')).toBe(true);
});
it('reports unavailable clipboard access', async () => {
  api.selectSite('family');
  vi.spyOn(api, 'getFolder').mockResolvedValue({ id: 'reports', path: 'Reports' } as Awaited<ReturnType<typeof api.getFolder>>);
  vi.stubGlobal('navigator', { clipboard: { writeText: vi.fn().mockRejectedValue(new Error('Denied')) } });
  render(<CopyFolderLink folderId="reports" />);
  await waitFor(() => expect(screen.getByRole('button', { name: 'Copy folder link' }).hasAttribute('disabled')).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Copy folder link' }));
  await screen.findByText(/Could not copy the link/);
  expect(screen.getByRole('button', { name: 'Copy folder link' }).hasAttribute('disabled')).toBe(false);
});
it('does not copy a late folder response after the dialog closes', async () => {
  let finish!: (folder: Awaited<ReturnType<typeof api.getFolder>>) => void;
  vi.spyOn(api, 'getFolder').mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  const writeText = vi.fn();
  vi.stubGlobal('navigator', { clipboard: { writeText } });
  const view = render(<CopyFolderLink folderId="reports" />);
  view.unmount();
  await act(async () => finish({ path: 'Reports' } as Awaited<ReturnType<typeof api.getFolder>>));
  expect(writeText).not.toHaveBeenCalled();
});

it('copies the hostname-resolved space synchronously in the click gesture', async () => {
  api.selectSite(null);
  vi.spyOn(api, 'getFolder').mockResolvedValue({ id: 'reports', path: 'Reports' } as Awaited<ReturnType<typeof api.getFolder>>);
  vi.spyOn(api, 'listSites').mockResolvedValue([{ slug: 'hostname-space', name: 'Home', current: true }]);
  const writeText = vi.fn(async (_text: string) => {});
  vi.stubGlobal('navigator', { clipboard: { writeText } });
  render(<CopyFolderLink folderId="reports" />);
  await waitFor(() => expect(screen.getByRole('button', { name: 'Copy folder link' }).hasAttribute('disabled')).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Copy folder link' }));
  expect(writeText).toHaveBeenCalledOnce();
  const url = new URL(writeText.mock.calls[0]![0]);
  expect(url.searchParams.get('site')).toBe('hostname-space');
  expect(url.searchParams.get('folder')).toBe('reports');
  expect(screen.getByText(/stable folder ID/)).toBeTruthy();
  await screen.findByText('Folder link copied.');
});
it('separates lookup failures from clipboard failures and retries preparation', async () => {
  api.selectSite('family');
  vi.spyOn(api, 'getFolder').mockRejectedValueOnce(new Error('Not found')).mockResolvedValue({ id: 'reports', path: 'Renamed reports' } as Awaited<ReturnType<typeof api.getFolder>>);
  const writeText = vi.fn(async (_text: string) => {});
  vi.stubGlobal('navigator', { clipboard: { writeText } });
  render(<CopyFolderLink folderId="reports" />);
  await screen.findByRole('alert');
  expect(screen.getByRole('alert').textContent).toContain('Could not look up');
  expect(writeText).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: 'Retry folder lookup' }));
  await waitFor(() => expect(screen.getByRole('button', { name: 'Copy folder link' }).hasAttribute('disabled')).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Copy folder link' }));
  expect(new URL(writeText.mock.calls[0]![0]).searchParams.get('folder')).toBe('reports');
  await screen.findByText('Folder link copied.');
});
