import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { TextPreview } from './text-preview';
import { PreviewPanel } from './preview';
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it('toggles layout without altering or parsing the displayed text', () => {
  const text = '<script>alert(1)</script>\n  indented line';
  const { container } = render(<TextPreview text={text} />);
  const pre = container.querySelector('pre')!;
  const toggle = screen.getByRole('button', { name: 'Wrap lines' });
  expect(toggle.getAttribute('aria-pressed')).toBe('true');
  expect(pre.className).toContain('overflow-wrap:anywhere');
  fireEvent.click(toggle);
  expect(toggle.getAttribute('aria-pressed')).toBe('false');
  expect(pre.className).toContain('whitespace-pre');
  expect(pre.className).not.toContain('pre-wrap');
  expect(pre.textContent).toBe(text);
  expect(container.querySelector('script')).toBeNull();
  fireEvent.click(toggle);
  expect(pre.textContent).toBe(text);
});
it('offers wrapping in the permission-checked text preview without refetching bytes', async () => {
  const fetch = vi.fn(async (url: string) => new Response(url.includes('/content') ? 'original\n  layout' : JSON.stringify({ file: { id: 'a', name: 'notes.txt' }, version: { id: 'v1', source: 'blob', mime: 'text/plain' }, canWrite: false })));
  vi.stubGlobal('fetch', fetch);
  render(<PreviewPanel fileId="a" onClose={() => {}} onError={() => {}} />);
  const toggle = await screen.findByRole('button', { name: 'Wrap lines' });
  const requests = fetch.mock.calls.length;
  fireEvent.click(toggle);
  expect(toggle.getAttribute('aria-pressed')).toBe('false');
  expect(fetch).toHaveBeenCalledTimes(requests);
  expect(screen.queryByRole('button', { name: 'Edit text' })).toBeNull();
});
